// Generates the tools table in README.md from src/tools.json.
// Re-run whenever tools.json changes (new tool, category change, etc.):
//
//   npm run generate:readme
//
// The generated block is wrapped in BEGIN/END sentinel comments so re-runs
// replace the region in place instead of appending.

import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const log = (...args) => console.log('[generate-readme]', ...args);

const GENERATED_NOTE = 'generated by scripts/generate-readme.mjs — re-run after editing tools.json';

const { tools } = JSON.parse(readFileSync(resolve(root, 'src', 'tools.json'), 'utf8'));

const publicTools = tools.filter((t) => !t.internal);

// Group by category, preserving tools.json order
const byCategory = new Map();
for (const tool of publicTools) {
  const cat = tool.category || 'Other';
  if (!byCategory.has(cat)) byCategory.set(cat, []);
  byCategory.get(cat).push(tool);
}

function categoryBlock(category, categoryTools) {
  const rows = categoryTools
    .map((t) => `| ${t.icon} [${t.name}](src/${t.slug}.html) | ${t.card || t.description} |`)
    .join('\n');
  return [`### ${category}`, '', '| Tool | Description |', '|------|-------------|', rows].join('\n');
}

const sections = [...byCategory.entries()].map(([cat, catTools]) => categoryBlock(cat, catTools));
const blockInner = sections.join('\n\n');
const block =
  `<!-- BEGIN:tools-table ${GENERATED_NOTE} -->\n` +
  `${blockInner}\n` +
  `<!-- END:tools-table -->`;

const readmePath = resolve(root, 'README.md');
const original = readFileSync(readmePath, 'utf8');

const blockRe = /<!-- BEGIN:tools-table\b[^>]*-->[\s\S]*?<!-- END:tools-table -->/;
if (!blockRe.test(original)) {
  throw new Error(
    '[generate-readme] sentinel "<!-- BEGIN:tools-table -->" not found in README.md — add it first',
  );
}

const next = original.replace(blockRe, block);

if (next !== original) {
  writeFileSync(readmePath, next);
  log('✏️  README.md');
} else {
  log('✓ README.md (no changes)');
}
log('🎉 done');
