// Generates the tool-grid sections in src/index.html from src/tools.json.
// Re-run whenever tools.json changes (new tool, category change, etc.):
//
//   npm run generate:index
//
// The generated block is wrapped in BEGIN/END sentinel comments so re-runs
// replace the region in place instead of appending. On a first run (no
// sentinel present) the block is inserted immediately before the
// "<!-- Why section -->" comment.
//
// Each tool entry may carry an optional `card` field — a short one-liner for
// the index card. If absent, the full `description` is used.

import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const srcDir = resolve(root, 'src');

const log = (...args) => console.log('[generate-index]', ...args);

const GENERATED_NOTE =
  'generated by scripts/generate-index.mjs — re-run after editing tools.json';

const tools = JSON.parse(readFileSync(resolve(srcDir, 'tools.json'), 'utf8'));

const escHtml = s =>
  String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

function toolCard(tool) {
  const desc = tool.card || tool.description;
  return [
    `          <a`,
    `            href="${tool.slug}.html"`,
    `            class="card card-lift p-6"`,
    `          >`,
    `            <div class="text-3xl mb-3">${tool.icon}</div>`,
    `            <h2 class="text-sm font-semibold text-gray-200 mb-1.5">${escHtml(tool.name)}</h2>`,
    `            <p class="text-xs text-gray-500 leading-relaxed">`,
    `              ${escHtml(desc)}`,
    `            </p>`,
    `          </a>`,
  ].join('\n');
}

function categorySection(category, categoryTools, isLast) {
  const mb = isLast ? 'mb-20' : 'mb-12';
  const cards = categoryTools.map(toolCard).join('\n\n');
  return [
    `      <section class="${mb}">`,
    `        <div class="flex items-center gap-3 mb-4">`,
    `          <span class="text-xs font-semibold text-gray-500 uppercase tracking-widest">${escHtml(category)}</span>`,
    `          <div class="flex-1 h-px bg-gray-800"></div>`,
    `        </div>`,
    `        <div class="grid grid-cols-[repeat(auto-fill,minmax(200px,1fr))] gap-4">`,
    cards,
    `        </div>`,
    `      </section>`,
  ].join('\n');
}

// Only public tools; preserve tools.json order for both categories and tools
const publicTools = tools.tools.filter(t => !t.internal);
const byCategory = new Map();
for (const tool of publicTools) {
  const cat = tool.category || 'Other';
  if (!byCategory.has(cat)) byCategory.set(cat, []);
  byCategory.get(cat).push(tool);
}

const categories = [...byCategory.keys()];
const sections = categories.map((cat, i) =>
  categorySection(cat, byCategory.get(cat), i === categories.length - 1),
);

// Assemble the sentinel-wrapped block (6-space indent matches surrounding HTML)
const INDENT = '      ';
const blockInner = sections.join('\n\n');
const block =
  `${INDENT}<!-- BEGIN:tool-grid ${GENERATED_NOTE} -->\n` +
  `${blockInner}\n` +
  `${INDENT}<!-- END:tool-grid -->`;

const indexPath = resolve(srcDir, 'index.html');
const original = readFileSync(indexPath, 'utf8');

const blockRe = /[ \t]*<!-- BEGIN:tool-grid\b[^>]*-->[\s\S]*?<!-- END:tool-grid -->/;
let next;
if (blockRe.test(original)) {
  next = original.replace(blockRe, block);
} else {
  // First run: insert immediately before the static "Why section" block
  const anchorRe = /[ \t]*<!-- Why section -->/;
  const m = original.match(anchorRe);
  if (!m) {
    throw new Error(
      '[generate-index] anchor "<!-- Why section -->" not found in index.html — add it or update this script',
    );
  }
  next = original.slice(0, m.index) + block + '\n\n' + original.slice(m.index);
}

if (next !== original) {
  writeFileSync(indexPath, next);
  log('✏️  index.html');
} else {
  log('✓ index.html (no changes)');
}
log('🎉 done');
